

import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import normalize

INPUT_PATH = Path("jobs_data_clean.json")
OUTPUT_PATH = Path("jobs_with_embeddings.json")
METADATA_PATH = Path("jobs_with_embeddings.metadata.json")
DIM = 384
MAX_FIELD_CHARS = 500

SANDBOX_WARNING = (
    "DEMO DATA: embeddings generated by the TF-IDF+SVD sandbox fallback "
    "(no route to huggingface.co in this environment), NOT the production "
    "all-MiniLM-L6-v2 model. Match rankings here are NOT representative of "
    "production quality — plumbing/UI testing only."
)


def truncate(text, max_chars=MAX_FIELD_CHARS):
    return text[:max_chars] if text else text


def main():
    print("=" * 78)
    print("⚠️  " + SANDBOX_WARNING)
    print("=" * 78)

    jobs = json.loads(INPUT_PATH.read_text(encoding="utf-8"))
    texts = [job.get("full_text", "") for job in jobs]

    vectorizer = TfidfVectorizer(max_features=20000, stop_words="english", ngram_range=(1, 2))
    tfidf = vectorizer.fit_transform(texts)

    n_components = min(DIM, tfidf.shape[0] - 1, tfidf.shape[1])
    svd = TruncatedSVD(n_components=n_components, random_state=42)
    reduced = svd.fit_transform(tfidf)
    if n_components < DIM:
        print(
            f"NOTE: only {tfidf.shape[0]} documents available, so TruncatedSVD can produce at "
            f"most {n_components} independent components; zero-padding to {DIM}-dim for shape "
            f"parity with the real model's output."
        )
        pad = np.zeros((reduced.shape[0], DIM - n_components), dtype=reduced.dtype)
        reduced = np.hstack([reduced, pad])
    reduced = normalize(reduced)  # unit-norm, so cosine sim == dot product

    out = []
    for job, vec in zip(jobs, reduced):
        record = dict(job)
        record["description_clean"] = truncate(record.get("description_clean"))
        record["requirements_clean"] = truncate(record.get("requirements_clean"))
        record["embedding"] = vec.astype(np.float32).tolist()
        out.append(record)

    bad_dim = [r["id"] for r in out if len(r["embedding"]) != DIM]
    bad_norm = [r["id"] for r in out if not np.isclose(np.linalg.norm(r["embedding"]), 1.0, atol=1e-2)]
    if bad_dim or bad_norm:
        msg = []
        if bad_dim:
            msg.append(f"  wrong dimension ({len(bad_dim)}): {bad_dim[:10]}")
        if bad_norm:
            msg.append(f"  non-unit norm ({len(bad_norm)}): {bad_norm[:10]}")
        raise SystemExit("Sandbox embedding validation FAILED:\n" + "\n".join(msg))
    print(f"Validation passed: all {len(out)} embeddings are {DIM}-dim and unit-norm.")

    OUTPUT_PATH.write_text(json.dumps(out))
    print(f"Wrote {len(out)} records, {DIM}-dim embeddings -> {OUTPUT_PATH}")



    metadata = {
        "model_name": "tfidf-svd-sandbox-fallback",
        "model_revision": "n/a",
        "embedding_dim": DIM,
        "pooling": "n/a (SVD components, not transformer pooling)",
        "normalization": "l2",
        "max_tokens": "n/a (TfidfVectorizer, not a tokenizer-limited model)",
        "record_count": len(out),
        "sklearn_version": sklearn.__version__,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "is_sandbox_demo": True,
        "warning": SANDBOX_WARNING,
    }
    METADATA_PATH.write_text(json.dumps(metadata, indent=2))
    print(f"Wrote {METADATA_PATH} with is_sandbox_demo=true — UI/logs reading this file "
          f"should show a persistent warning banner while it's true.")
    print("=" * 78)
    print("⚠️  Remember: swap in the real generate_embeddings.py output before deploying.")
    print("=" * 78)


if __name__ == "__main__":
    main()
